/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  CompanySchema,
  CompanySearchResultSchema,
  CompanySearchSchema,
  GetByTicker400,
  Search400
} from '../litestarAPI.schemas';

import { customInstance } from '.././custom-instance';




/**
 * @summary GetByTicker
 */
export const getByTicker = (
    ticker: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CompanySchema>(
      {url: `/api/company/${ticker}`, method: 'GET', signal
    },
      );
    }
  



export const getGetByTickerQueryKey = (ticker?: string,) => {
    return [
    `/api/company/${ticker}`
    ] as const;
    }

    
export const getGetByTickerQueryOptions = <TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByTickerQueryKey(ticker);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getByTicker>>> = ({ signal }) => getByTicker(ticker, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(ticker), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetByTickerQueryResult = NonNullable<Awaited<ReturnType<typeof getByTicker>>>
export type GetByTickerQueryError = GetByTicker400


export function useGetByTicker<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByTicker>>,
          TError,
          Awaited<ReturnType<typeof getByTicker>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByTicker<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getByTicker>>,
          TError,
          Awaited<ReturnType<typeof getByTicker>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByTicker<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetByTicker
 */

export function useGetByTicker<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetByTickerQueryOptions(ticker,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetByTickerSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(ticker: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetByTickerQueryKey(ticker);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getByTicker>>> = ({ signal }) => getByTicker(ticker, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetByTickerSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getByTicker>>>
export type GetByTickerSuspenseQueryError = GetByTicker400


export function useGetByTickerSuspense<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByTickerSuspense<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetByTickerSuspense<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GetByTicker
 */

export function useGetByTickerSuspense<TData = Awaited<ReturnType<typeof getByTicker>>, TError = GetByTicker400>(
 ticker: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getByTicker>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetByTickerSuspenseQueryOptions(ticker,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Search
 */
export const search = (
    companySearchSchema: CompanySearchSchema,
 signal?: AbortSignal
) => {
      
      
      return customInstance<CompanySearchResultSchema[]>(
      {url: `/api/company/search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: companySearchSchema, signal
    },
      );
    }
  


export const getSearchMutationOptions = <TError = Search400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: CompanySearchSchema}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: CompanySearchSchema}, TContext> => {

const mutationKey = ['search'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof search>>, {data: CompanySearchSchema}> = (props) => {
          const {data} = props ?? {};

          return  search(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SearchMutationResult = NonNullable<Awaited<ReturnType<typeof search>>>
    export type SearchMutationBody = CompanySearchSchema
    export type SearchMutationError = Search400

    /**
 * @summary Search
 */
export const useSearch = <TError = Search400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof search>>, TError,{data: CompanySearchSchema}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof search>>,
        TError,
        {data: CompanySearchSchema},
        TContext
      > => {

      const mutationOptions = getSearchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    