services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=litestar
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stonks-net

volumes:
  pgdata:

networks:
  stonks-net:
    driver: bridge
