services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=litestar
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c shared_preload_libraries='pg_cron' -c cron.database_name='app'

volumes:
  pgdata:
