services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=litestar
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
