// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetHealthData, GetHealthResponse, GetCompanyByTickerData, GetCompanyByTickerResponse, PostCompanySearchData, PostCompanySearchResponse } from './types.gen';

export class DefaultService {
    /**
     * HealthCheck
     * @param data The data for the request.
     * @param data.includeInSchema
     * @returns string Request fulfilled, document follows
     * @throws ApiError
     */
    public static getHealth(data: GetHealthData = {}): CancelablePromise<GetHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health',
            query: {
                include_in_schema: data.includeInSchema
            },
            errors: {
                400: 'Bad request syntax or unsupported method'
            }
        });
    }
    
}

export class CompanyService {
    /**
     * GetByTicker
     * @param data The data for the request.
     * @param data.ticker
     * @returns CompanySchema Request fulfilled, document follows
     * @throws ApiError
     */
    public static getCompanyByTicker(data: GetCompanyByTickerData): CancelablePromise<GetCompanyByTickerResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/company/{ticker}',
            path: {
                ticker: data.ticker
            },
            errors: {
                400: 'Bad request syntax or unsupported method'
            }
        });
    }
    
    /**
     * Search
     * @param data The data for the request.
     * @param data.requestBody
     * @returns CompanySearchResultSchema Document created, URL follows
     * @throws ApiError
     */
    public static postCompanySearch(data: PostCompanySearchData): CancelablePromise<PostCompanySearchResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/company/search',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Bad request syntax or unsupported method'
            }
        });
    }
    
}