// This file is auto-generated by @hey-api/openapi-ts

export type CompanyComparablesSchema = {
  median_ev_to_revenue?: number | null;
  median_ev_to_ebitda?: number | null;
  median_pe_ratio?: number | null;
};

export type CompanyPredictionsSchema = {
  projected_5y_share_price?: number | null;
};

export type CompanySchema = {
  id: string;
  name: string;
  ticker: string;
  industry?: string | null;
  filings: Array<FilingSchema>;
  latest_filing?: FilingSchema | null;
  stats?: CompanyStatsSchema | null;
  comparables?: CompanyComparablesSchema | null;
  predictions?: CompanyPredictionsSchema | null;
  created_at: string;
  updated_at: string;
};

export type CompanySearchFilters = {
  industries?: Array<string> | null;
  subIndustries?: Array<string> | null;
  numericRanges?: {
    [key: string]: NumericRange;
  } | null;
};

export type CompanySearchResultSchema = {
  id: string;
  name: string;
  ticker: string;
  industry?: string | null;
  equity_value?: number | null;
  ltm_revenue?: number | null;
  multiple_ev_to_revenue?: number | null;
  created_at: string;
  updated_at: string;
};

export type CompanySearchSchema = {
  search?: string | null;
  filters?: CompanySearchFilters | null;
  sorting?: Array<SortCriterion> | null;
  pagination?: Pagination | null;
};

export type CompanyStatsSchema = {
  ltm_revenue?: number | null;
  ltm_revenue_growth?: number | null;
  ltm_net_income?: number | null;
  ltm_ebitda?: number | null;
  share_price?: number | null;
  shares_outstanding?: number | null;
  equity_value?: number | null;
  cash?: number | null;
  debt?: number | null;
  enterprise_value?: number | null;
  multiple_ev_to_revenue?: number | null;
  multiple_ev_to_ebitda?: number | null;
  price_to_earnings?: number | null;
  median_fund_investment_percentage_change?: number | null;
};

export type FilingSchema = {
  id: string;
  cik: string;
  company_id: string;
  type: "10-Q" | "10-K";
  period_end: string;
  filing_date: string;
  revenue?: number | null;
  net_income?: number | null;
  ebitda?: number | null;
  shares_outstanding?: number | null;
  cash?: number | null;
  debt?: number | null;
  document_url?: string | null;
  source?: "EDGAR" | "Manual" | "Other" | null;
  created_at: string;
  updated_at: string;
};

export type type = "10-Q" | "10-K";

export type source = "EDGAR" | "Manual" | "Other";

export type NumericRange = {
  min?: number | null;
  max?: number | null;
};

export type Pagination = {
  offset?: number | null;
  limit?: number | null;
};

export type SortCriterion = {
  field: string;
  direction: "asc" | "desc";
};

export type direction = "asc" | "desc";

export type GetHealthData = {
  includeInSchema?: boolean;
};

export type GetHealthResponse = string;

export type GetCompanyByTickerData = {
  ticker: string;
};

export type GetCompanyByTickerResponse = CompanySchema;

export type PostCompanySearchData = {
  requestBody: CompanySearchSchema;
};

export type PostCompanySearchResponse = Array<CompanySearchResultSchema>;

export type $OpenApiTs = {
  "/health": {
    get: {
      req: GetHealthData;
      res: {
        /**
         * Request fulfilled, document follows
         */
        200: string;
        /**
         * Bad request syntax or unsupported method
         */
        400: {
          status_code: number;
          detail: string;
          extra?: {
            [key: string]: unknown;
          } | null;
        };
      };
    };
  };
  "/company/{ticker}": {
    get: {
      req: GetCompanyByTickerData;
      res: {
        /**
         * Request fulfilled, document follows
         */
        200: CompanySchema;
        /**
         * Bad request syntax or unsupported method
         */
        400: {
          status_code: number;
          detail: string;
          extra?: {
            [key: string]: unknown;
          } | null;
        };
      };
    };
  };
  "/company/search": {
    post: {
      req: PostCompanySearchData;
      res: {
        /**
         * Document created, URL follows
         */
        201: Array<CompanySearchResultSchema>;
        /**
         * Bad request syntax or unsupported method
         */
        400: {
          status_code: number;
          detail: string;
          extra?: {
            [key: string]: unknown;
          } | null;
        };
      };
    };
  };
};
