/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Litestar API
 * OpenAPI spec version: 1.0.0
 */
export type CompanyComparablesSchemaMedianEvToRevenue = number | null;

export type CompanyComparablesSchemaMedianEvToEbitda = number | null;

export type CompanyComparablesSchemaMedianPeRatio = number | null;

export interface CompanyComparablesSchema {
  median_ev_to_revenue?: CompanyComparablesSchemaMedianEvToRevenue;
  median_ev_to_ebitda?: CompanyComparablesSchemaMedianEvToEbitda;
  median_pe_ratio?: CompanyComparablesSchemaMedianPeRatio;
}

export type CompanyPredictionsSchemaProjected5ySharePrice = number | null;

export interface CompanyPredictionsSchema {
  projected_5y_share_price?: CompanyPredictionsSchemaProjected5ySharePrice;
}

export type CompanySchemaIndustry = string | null;

export type CompanySchemaLatestFiling = FilingSchema | null;

export type CompanySchemaStats = CompanyStatsSchema | null;

export type CompanySchemaComparables = CompanyComparablesSchema | null;

export type CompanySchemaPredictions = CompanyPredictionsSchema | null;

export interface CompanySchema {
  id: string;
  name: string;
  ticker: string;
  industry?: CompanySchemaIndustry;
  filings: FilingSchema[];
  latest_filing?: CompanySchemaLatestFiling;
  stats?: CompanySchemaStats;
  comparables?: CompanySchemaComparables;
  predictions?: CompanySchemaPredictions;
  created_at: string;
  updated_at: string;
}

export type CompanySearchFiltersIndustries = string[] | null;

export type CompanySearchFiltersSubIndustries = string[] | null;

export type CompanySearchFiltersNumericRangesOneOf = {[key: string]: NumericRange};

export type CompanySearchFiltersNumericRanges = CompanySearchFiltersNumericRangesOneOf | null;

export interface CompanySearchFilters {
  industries?: CompanySearchFiltersIndustries;
  subIndustries?: CompanySearchFiltersSubIndustries;
  numericRanges?: CompanySearchFiltersNumericRanges;
}

export type CompanySearchResultSchemaIndustry = string | null;

export type CompanySearchResultSchemaEquityValue = number | null;

export type CompanySearchResultSchemaLtmRevenue = number | null;

export type CompanySearchResultSchemaMultipleEvToRevenue = number | null;

export interface CompanySearchResultSchema {
  id: string;
  name: string;
  ticker: string;
  industry?: CompanySearchResultSchemaIndustry;
  equity_value?: CompanySearchResultSchemaEquityValue;
  ltm_revenue?: CompanySearchResultSchemaLtmRevenue;
  multiple_ev_to_revenue?: CompanySearchResultSchemaMultipleEvToRevenue;
  created_at: string;
  updated_at: string;
}

export type CompanySearchSchemaSearch = string | null;

export type CompanySearchSchemaFilters = CompanySearchFilters | null;

export type CompanySearchSchemaSorting = SortCriterion[] | null;

export type CompanySearchSchemaPagination = Pagination | null;

export interface CompanySearchSchema {
  search?: CompanySearchSchemaSearch;
  filters?: CompanySearchSchemaFilters;
  sorting?: CompanySearchSchemaSorting;
  pagination?: CompanySearchSchemaPagination;
}

export type CompanyStatsSchemaLtmRevenue = number | null;

export type CompanyStatsSchemaLtmRevenueGrowth = number | null;

export type CompanyStatsSchemaLtmNetIncome = number | null;

export type CompanyStatsSchemaLtmEbitda = number | null;

export type CompanyStatsSchemaSharePrice = number | null;

export type CompanyStatsSchemaSharesOutstanding = number | null;

export type CompanyStatsSchemaEquityValue = number | null;

export type CompanyStatsSchemaCash = number | null;

export type CompanyStatsSchemaDebt = number | null;

export type CompanyStatsSchemaEnterpriseValue = number | null;

export type CompanyStatsSchemaMultipleEvToRevenue = number | null;

export type CompanyStatsSchemaMultipleEvToEbitda = number | null;

export type CompanyStatsSchemaPriceToEarnings = number | null;

export type CompanyStatsSchemaMedianFundInvestmentPercentageChange = number | null;

export interface CompanyStatsSchema {
  ltm_revenue?: CompanyStatsSchemaLtmRevenue;
  ltm_revenue_growth?: CompanyStatsSchemaLtmRevenueGrowth;
  ltm_net_income?: CompanyStatsSchemaLtmNetIncome;
  ltm_ebitda?: CompanyStatsSchemaLtmEbitda;
  share_price?: CompanyStatsSchemaSharePrice;
  shares_outstanding?: CompanyStatsSchemaSharesOutstanding;
  equity_value?: CompanyStatsSchemaEquityValue;
  cash?: CompanyStatsSchemaCash;
  debt?: CompanyStatsSchemaDebt;
  enterprise_value?: CompanyStatsSchemaEnterpriseValue;
  multiple_ev_to_revenue?: CompanyStatsSchemaMultipleEvToRevenue;
  multiple_ev_to_ebitda?: CompanyStatsSchemaMultipleEvToEbitda;
  price_to_earnings?: CompanyStatsSchemaPriceToEarnings;
  median_fund_investment_percentage_change?: CompanyStatsSchemaMedianFundInvestmentPercentageChange;
}

export type FilingSchemaType = typeof FilingSchemaType[keyof typeof FilingSchemaType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilingSchemaType = {
  '10-Q': '10-Q',
  '10-K': '10-K',
} as const;

export type FilingSchemaRevenue = number | null;

export type FilingSchemaNetIncome = number | null;

export type FilingSchemaEbitda = number | null;

export type FilingSchemaSharesOutstanding = number | null;

export type FilingSchemaCash = number | null;

export type FilingSchemaDebt = number | null;

export type FilingSchemaDocumentUrl = string | null;

export type FilingSchemaSource = 'EDGAR' | 'Manual' | 'Other' | null;

export interface FilingSchema {
  id: string;
  cik: string;
  company_id: string;
  type: FilingSchemaType;
  period_end: string;
  filing_date: string;
  revenue?: FilingSchemaRevenue;
  net_income?: FilingSchemaNetIncome;
  ebitda?: FilingSchemaEbitda;
  shares_outstanding?: FilingSchemaSharesOutstanding;
  cash?: FilingSchemaCash;
  debt?: FilingSchemaDebt;
  document_url?: FilingSchemaDocumentUrl;
  source?: FilingSchemaSource;
  created_at: string;
  updated_at: string;
}

export type NumericRangeMin = number | null;

export type NumericRangeMax = number | null;

export interface NumericRange {
  min?: NumericRangeMin;
  max?: NumericRangeMax;
}

export type PaginationOffset = number | null;

export type PaginationLimit = number | null;

export interface Pagination {
  offset?: PaginationOffset;
  limit?: PaginationLimit;
}

export type SortCriterionDirection = typeof SortCriterionDirection[keyof typeof SortCriterionDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SortCriterionDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;

export interface SortCriterion {
  field: string;
  direction: SortCriterionDirection;
}

export type GetByTicker400ExtraAnyOf = {[key: string]: unknown};

export type GetByTicker400Extra = null | GetByTicker400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GetByTicker400 = {
  status_code: number;
  detail: string;
  extra?: GetByTicker400Extra;
};

export type Search400ExtraAnyOf = {[key: string]: unknown};

export type Search400Extra = null | Search400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type Search400 = {
  status_code: number;
  detail: string;
  extra?: Search400Extra;
};

