name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Home Server Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest

      - name: Call Home Server Webhook
        run: |
          curl -X POST http://walter:9000/webhook \
            -H "Content-Type: application/json" \
            -d '{"trigger": "github-actions"}'
